#!/usr/bin/env python3
"""
Plot foot trajectories (x, z) for two different mu values (mu=1 and mu=2)
in the same figure for comparison, with annotations for gc, gp, and d_step.
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker

# ----------------- Parameters -----------------
a = 150.0             # gain parameter for radius dynamics
omega = 6.28          # rad/s
h = 0.3               # base height (m)
gc = 0.12              # swing amplitude (m)
gp = 0.03            # stance amplitude (m)
d_step = 0.1          # step length scaling
dt = 0.001            # time step
T = 2.0               # total simulation time (s)
time = np.arange(0, T, dt)

mu_values = [1.5, 2.0]  # two test cases
colors = ['#1f77b4', '#ff7f0e']  # blue / orange


# ----------------- Simulation Function -----------------
def simulate_cpg(mu):
    """Simulate the CPG foot trajectory for a given mu."""
    r = mu
    dr = 0.0
    theta = 0.0

    x_list, z_list = [], []

    for _ in time:
        # CPG dynamics
        dd_r = a * ((a / 4.0) * (mu - r) - dr)
        dr += dd_r * dt
        r += dr * dt
        theta += omega * dt

        # Foot trajectory
        x = -d_step * (r-1) * np.cos(theta)
        sin_theta = np.sin(theta)
        if sin_theta > 0:
            z = -h + gc * sin_theta  # swing
        else:
            z = -h + gp * sin_theta  # stance

        x_list.append(x)
        z_list.append(z + h)

    return np.array(x_list), np.array(z_list)


# ----------------- Plot -----------------
plt.figure(figsize=(7, 5))

# 绘制轨迹曲线
for mu, color in zip(mu_values, colors):
    x, z = simulate_cpg(mu)
    plt.plot(x, z, color=color, linewidth=2.5, label=fr"$\mu = {mu}$")

# ======== 绘制参数箭头示意 ========
# gc: (0,0) -> (0,0.10)
plt.annotate(
    "", xy=(0.0, gc), xytext=(0.0, 0.0),
    arrowprops=dict(arrowstyle="<->", color="black", linestyle="--", linewidth=2)
)
plt.text(0.01, 0.05, r"$g_c$", color="black", fontsize=15, va="center")

# gp: (0,0) -> (0,-0.03)
plt.annotate(
    "", xy=(0.0, -gp), xytext=(0.0, 0.0),
    arrowprops=dict(arrowstyle="<->", color="black", linestyle="--", linewidth=2)
)
plt.text(0.01, -0.01, r"$g_p$", color="black", fontsize=15, va="center")

# d_step: (0,0) -> (-0.2,0)
plt.annotate(
    "", xy=(-d_step, 0.0), xytext=(0.0, 0.0),
    arrowprops=dict(arrowstyle="<->", color="black", linestyle="--", linewidth=2)
)
plt.text(-0.07, 0.01, r"$d_{\mathrm{step}}$", color="black", fontsize=15, ha="center")

# ======== 其他美化 ========
plt.axhline(0, color="gray", linestyle=":", linewidth=1)
plt.axvline(0, color="gray", linestyle=":", linewidth=1)
plt.xlabel("x [m]", fontsize=14)
plt.ylabel("z [m]", fontsize=14)
plt.title("Foot trajectories generated by CPG", fontsize=15)
plt.legend(fontsize=10,loc="upper right")
plt.grid(True, linestyle="--", alpha=0.6)
plt.tick_params(axis='x', labelsize=14)
plt.tick_params(axis='y', labelsize=14)
plt.gca().set_aspect("equal", adjustable="box")
ax = plt.gca()
ax.xaxis.set_major_locator(ticker.MultipleLocator(0.05))
ax.yaxis.set_major_locator(ticker.MultipleLocator(0.05))
plt.tight_layout()
save_path = "/home/song/cpg_jump/deploy/figures/cpg_params.png"
plt.savefig(save_path, dpi=100,bbox_inches='tight')
plt.show()
